import type { WorkspaceData } from "./types";

export const seedData: WorkspaceData = {
  clients: [
    {
      id: "client-1",
      name: "Constructora Norte S.A.S.",
      contactName: "Laura Mejia",
      email: "laura@constructoranorte.co",
      phone: "300 123 4567",
      createdAt: "2026-07-01T09:00:00.000Z",
    },
    {
      id: "client-2",
      name: "Andes Foods",
      contactName: "Carlos Rojas",
      email: "carlos@andesfoods.co",
      phone: "310 555 0140",
      createdAt: "2026-07-02T11:30:00.000Z",
    },
  ],
  cases: [
    {
      id: "case-1",
      clientId: "client-1",
      trackingCode: "AS-2026-001",
      title: "Licitacion municipal 2026",
      description: "Revision de pliegos, requisitos habilitantes y observaciones.",
      status: "requiere_cliente",
      priority: "alta",
      responsible: "Daniela Torres",
      nextStep: "Recibir certificado de experiencia actualizado.",
      createdAt: "2026-07-01T10:00:00.000Z",
      updatedAt: "2026-07-04T14:15:00.000Z",
    },
    {
      id: "case-2",
      clientId: "client-1",
      trackingCode: "AS-2026-002",
      title: "Contrato de obra con proveedor",
      description: "Ajuste de clausulas de responsabilidad, pagos y terminacion.",
      status: "en_curso",
      priority: "normal",
      responsible: "Martin Acosta",
      nextStep: "Enviar version marcada al cliente.",
      createdAt: "2026-06-28T15:20:00.000Z",
      updatedAt: "2026-07-03T16:45:00.000Z",
    },
    {
      id: "case-3",
      clientId: "client-2",
      trackingCode: "AS-2026-003",
      title: "Concepto laboral sobre turnos",
      description: "Analisis de modificacion de turnos y riesgos laborales.",
      status: "en_espera",
      priority: "normal",
      responsible: "Sofia Bernal",
      nextStep: "Esperar informacion de nomina solicitada.",
      createdAt: "2026-07-02T13:00:00.000Z",
      updatedAt: "2026-07-03T09:10:00.000Z",
    },
  ],
  milestones: [
    {
      id: "milestone-1",
      caseId: "case-1",
      title: "Apertura del asunto",
      description: "La firma registro el asunto y asigno el equipo responsable.",
      detail:
        "Se valido la informacion inicial del cliente, el objetivo del proceso y los responsables de seguimiento.",
      date: "2026-07-01",
      status: "completed",
      evidenceEnabled: false,
    },
    {
      id: "milestone-2",
      caseId: "case-1",
      title: "Revision inicial de pliegos",
      description: "Se revisaron requisitos habilitantes y documentos disponibles.",
      detail:
        "El equipo identifico los documentos que ya cumplen y marco los faltantes para completar la presentacion.",
      date: "2026-07-03",
      status: "completed",
      evidenceEnabled: false,
    },
    {
      id: "milestone-3",
      caseId: "case-1",
      title: "Recoleccion de evidencia",
      description:
        "Estamos esperando el certificado de experiencia actualizado para continuar con observaciones.",
      detail:
        "Cuando el cliente cargue el soporte, el equipo lo revisara y definira si queda listo para radicar.",
      date: "2026-07-08",
      status: "current",
      evidenceEnabled: true,
    },
    {
      id: "milestone-4",
      caseId: "case-1",
      title: "Radicacion de observaciones",
      description: "La firma preparara y radicara observaciones si aplica.",
      detail:
        "Esta etapa depende de completar la informacion pendiente y validar la estrategia final.",
      date: "2026-07-10",
      status: "upcoming",
      evidenceEnabled: false,
    },
    {
      id: "milestone-5",
      caseId: "case-1",
      title: "Seguimiento a respuesta",
      description: "Se hara seguimiento a la respuesta de la entidad.",
      detail:
        "La firma informara cualquier decision relevante y los siguientes pasos del proceso.",
      date: "2026-07-15",
      status: "upcoming",
      evidenceEnabled: false,
    },
    {
      id: "milestone-6",
      caseId: "case-2",
      title: "Recepcion de minuta",
      description: "La firma recibio y clasifico la minuta enviada por el cliente.",
      detail: "El documento quedo asociado al asunto para revision contractual.",
      date: "2026-06-28",
      status: "completed",
      evidenceEnabled: false,
    },
    {
      id: "milestone-7",
      caseId: "case-2",
      title: "Revision contractual",
      description: "Estamos ajustando clausulas de pagos, multas y terminacion.",
      detail:
        "El abogado responsable prepara una version marcada para compartir con el cliente.",
      date: "2026-07-04",
      status: "current",
      evidenceEnabled: false,
    },
    {
      id: "milestone-8",
      caseId: "case-2",
      title: "Aprobacion cliente",
      description: "El cliente revisara la version marcada y autorizara cierre.",
      detail: "La firma esperara comentarios finales antes de preparar version limpia.",
      date: "2026-07-07",
      status: "upcoming",
      evidenceEnabled: true,
    },
    {
      id: "milestone-9",
      caseId: "case-3",
      title: "Solicitud de informacion laboral",
      description: "Se solicito informacion de nomina y turnos.",
      detail: "El equipo requiere datos operativos para evaluar riesgos laborales.",
      date: "2026-07-03",
      status: "current",
      evidenceEnabled: true,
    },
    {
      id: "milestone-10",
      caseId: "case-3",
      title: "Emision de concepto",
      description: "La firma preparara concepto juridico con recomendaciones.",
      detail: "El concepto se publicara cuando se revise la informacion pendiente.",
      date: "2026-07-11",
      status: "upcoming",
      evidenceEnabled: false,
    },
  ],
  updates: [
    {
      id: "update-1",
      caseId: "case-1",
      author: "Daniela Torres",
      body: "Se revisaron los requisitos habilitantes y se identifico un documento pendiente.",
      visibility: "client",
      createdAt: "2026-07-04T14:15:00.000Z",
    },
    {
      id: "update-2",
      caseId: "case-1",
      author: "Daniela Torres",
      body: "Pendiente validar internamente si conviene presentar observacion adicional.",
      visibility: "internal",
      createdAt: "2026-07-04T14:25:00.000Z",
    },
    {
      id: "update-3",
      caseId: "case-2",
      author: "Martin Acosta",
      body: "Se ajustaron clausulas de pagos parciales y multas por incumplimiento.",
      visibility: "client",
      createdAt: "2026-07-03T16:45:00.000Z",
    },
  ],
  requests: [
    {
      id: "request-1",
      caseId: "case-1",
      title: "Certificado de experiencia",
      detail: "Enviar certificado actualizado en PDF.",
      owner: "Laura Mejia",
      dueDate: "2026-07-08",
      status: "pendiente",
      createdAt: "2026-07-04T14:20:00.000Z",
    },
    {
      id: "request-2",
      caseId: "case-3",
      title: "Reporte de turnos",
      detail: "Cargar archivo con turnos de los ultimos tres meses.",
      owner: "Carlos Rojas",
      dueDate: "2026-07-09",
      status: "en_progreso",
      createdAt: "2026-07-03T09:10:00.000Z",
    },
  ],
  documents: [
    {
      id: "doc-1",
      caseId: "case-1",
      name: "Pliego_condiciones_v2.pdf",
      category: "Licitacion",
      visibility: "client",
      status: "aprobado",
      uploadedAt: "2026-07-03T10:30:00.000Z",
    },
    {
      id: "doc-2",
      caseId: "case-2",
      name: "Contrato_obra_revision.docx",
      category: "Contrato",
      visibility: "client",
      status: "en_revision",
      uploadedAt: "2026-07-03T16:40:00.000Z",
    },
  ],
  audit: [
    {
      id: "audit-1",
      actor: "Sistema demo",
      action: "Cargo datos iniciales",
      target: "Workspace",
      createdAt: "2026-07-04T08:00:00.000Z",
    },
  ],
};
