import type { WorkspaceData } from "./types";

export const seedData: WorkspaceData = {
  clients: [
    {
      id: "client-1",
      name: "Constructora Norte S.A.S.",
      contactName: "Laura Mejia",
      email: "laura@constructoranorte.co",
      phone: "300 123 4567",
      createdAt: "2026-07-01T09:00:00.000Z",
    },
    {
      id: "client-2",
      name: "Andes Foods",
      contactName: "Carlos Rojas",
      email: "carlos@andesfoods.co",
      phone: "310 555 0140",
      createdAt: "2026-07-02T11:30:00.000Z",
    },
  ],
  cases: [
    {
      id: "case-1",
      clientId: "client-1",
      title: "Licitacion municipal 2026",
      description: "Revision de pliegos, requisitos habilitantes y observaciones.",
      status: "requiere_cliente",
      priority: "alta",
      responsible: "Daniela Torres",
      nextStep: "Recibir certificado de experiencia actualizado.",
      createdAt: "2026-07-01T10:00:00.000Z",
      updatedAt: "2026-07-04T14:15:00.000Z",
    },
    {
      id: "case-2",
      clientId: "client-1",
      title: "Contrato de obra con proveedor",
      description: "Ajuste de clausulas de responsabilidad, pagos y terminacion.",
      status: "en_curso",
      priority: "normal",
      responsible: "Martin Acosta",
      nextStep: "Enviar version marcada al cliente.",
      createdAt: "2026-06-28T15:20:00.000Z",
      updatedAt: "2026-07-03T16:45:00.000Z",
    },
    {
      id: "case-3",
      clientId: "client-2",
      title: "Concepto laboral sobre turnos",
      description: "Analisis de modificacion de turnos y riesgos laborales.",
      status: "en_espera",
      priority: "normal",
      responsible: "Sofia Bernal",
      nextStep: "Esperar informacion de nomina solicitada.",
      createdAt: "2026-07-02T13:00:00.000Z",
      updatedAt: "2026-07-03T09:10:00.000Z",
    },
  ],
  updates: [
    {
      id: "update-1",
      caseId: "case-1",
      author: "Daniela Torres",
      body: "Se revisaron los requisitos habilitantes y se identifico un documento pendiente.",
      visibility: "client",
      createdAt: "2026-07-04T14:15:00.000Z",
    },
    {
      id: "update-2",
      caseId: "case-1",
      author: "Daniela Torres",
      body: "Pendiente validar internamente si conviene presentar observacion adicional.",
      visibility: "internal",
      createdAt: "2026-07-04T14:25:00.000Z",
    },
    {
      id: "update-3",
      caseId: "case-2",
      author: "Martin Acosta",
      body: "Se ajustaron clausulas de pagos parciales y multas por incumplimiento.",
      visibility: "client",
      createdAt: "2026-07-03T16:45:00.000Z",
    },
  ],
  requests: [
    {
      id: "request-1",
      caseId: "case-1",
      title: "Certificado de experiencia",
      detail: "Enviar certificado actualizado en PDF.",
      owner: "Laura Mejia",
      dueDate: "2026-07-08",
      status: "pendiente",
      createdAt: "2026-07-04T14:20:00.000Z",
    },
    {
      id: "request-2",
      caseId: "case-3",
      title: "Reporte de turnos",
      detail: "Cargar archivo con turnos de los ultimos tres meses.",
      owner: "Carlos Rojas",
      dueDate: "2026-07-09",
      status: "en_progreso",
      createdAt: "2026-07-03T09:10:00.000Z",
    },
  ],
  documents: [
    {
      id: "doc-1",
      caseId: "case-1",
      name: "Pliego_condiciones_v2.pdf",
      category: "Licitacion",
      visibility: "client",
      status: "aprobado",
      uploadedAt: "2026-07-03T10:30:00.000Z",
    },
    {
      id: "doc-2",
      caseId: "case-2",
      name: "Contrato_obra_revision.docx",
      category: "Contrato",
      visibility: "client",
      status: "en_revision",
      uploadedAt: "2026-07-03T16:40:00.000Z",
    },
  ],
  audit: [
    {
      id: "audit-1",
      actor: "Sistema demo",
      action: "Cargo datos iniciales",
      target: "Workspace",
      createdAt: "2026-07-04T08:00:00.000Z",
    },
  ],
};
