"""add case opening date

Revision ID: 4d39af83fd4b
Revises: 0f79212eda55
Create Date: 2026-07-28 21:35:22.046676

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d39af83fd4b'
down_revision: Union[str, None] = '0f79212eda55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asuntos', sa.Column('fecha_apertura', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asuntos', 'fecha_apertura')
    # ### end Alembic commands ###
