"""add persistent auth challenges

Revision ID: 644b4f45f675
Revises: 698510deb624
Create Date: 2026-07-28 06:13:25.137990

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644b4f45f675'
down_revision: Union[str, None] = '698510deb624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_challenges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_challenges_expires_at'), 'auth_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_challenges_firma_id'), 'auth_challenges', ['firma_id'], unique=False)
    op.create_index(op.f('ix_auth_challenges_is_active'), 'auth_challenges', ['is_active'], unique=False)
    op.create_index(op.f('ix_auth_challenges_purpose'), 'auth_challenges', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_challenges_user_id'), 'auth_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_challenges_user_id'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_purpose'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_is_active'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_firma_id'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_expires_at'), table_name='auth_challenges')
    op.drop_table('auth_challenges')
    # ### end Alembic commands ###
