"""add sequential asunto workflow

Revision ID: 0f79212eda55
Revises: 644b4f45f675
Create Date: 2026-07-28 07:08:14.079837

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f79212eda55'
down_revision: Union[str, None] = '644b4f45f675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asunto_pasos',
    sa.Column('asunto_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('campos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asunto_id'], ['asuntos.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.UniqueConstraint('asunto_id', 'codigo', name='uq_asunto_paso_codigo'),
    sa.UniqueConstraint('asunto_id', 'orden', name='uq_asunto_paso_orden'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asunto_pasos_asunto_id'), 'asunto_pasos', ['asunto_id'], unique=False)
    op.create_index(op.f('ix_asunto_pasos_estado'), 'asunto_pasos', ['estado'], unique=False)
    op.create_index(op.f('ix_asunto_pasos_firma_id'), 'asunto_pasos', ['firma_id'], unique=False)
    op.create_index(op.f('ix_asunto_pasos_is_active'), 'asunto_pasos', ['is_active'], unique=False)
    op.add_column('asuntos', sa.Column('ruta_codigo', sa.String(length=80), server_default='insolvencia_persona_natural', nullable=False))
    op.add_column('asuntos', sa.Column('paso_actual', sa.Integer(), server_default='1', nullable=False))
    op.add_column('asuntos', sa.Column('flujo_estado', sa.String(length=30), server_default='activo', nullable=False))
    op.get_bind().exec_driver_sql(
        """
        INSERT INTO asunto_pasos (
            id, asunto_id, firma_id, orden, codigo, titulo, descripcion,
            estado, campos, datos, is_active, created_at, updated_at, created_by_id
        )
        SELECT
            gen_random_uuid(), a.id, a.firma_id, step.orden, step.codigo,
            step.titulo, step.descripcion,
            CASE WHEN step.orden = 1 THEN 'activo' ELSE 'bloqueado' END,
            step.campos::jsonb, '{}'::jsonb, true, now(), now(),
            COALESCE(a.created_by_id, a.abogado_id)
        FROM asuntos a
        CROSS JOIN (
            VALUES
              (1, 'radicacion', 'Radicación',
               'Registra la radicación oficial y la autoridad que recibe el trámite.',
               '[{"clave":"radicado_oficial","etiqueta":"Radicado oficial","tipo":"text","requerido":true},{"clave":"autoridad","etiqueta":"Centro de conciliación o notaría","tipo":"text","requerido":true},{"clave":"fecha_radicacion","etiqueta":"Fecha de radicación","tipo":"date","requerido":true}]'),
              (2, 'agendar_audiencia', 'Agendar audiencia',
               'Define fecha, hora y medio de la audiencia.',
               '[{"clave":"fecha_hora","etiqueta":"Fecha y hora","tipo":"datetime","requerido":true},{"clave":"modalidad","etiqueta":"Modalidad","tipo":"select","requerido":true,"opciones":[{"valor":"virtual","etiqueta":"Virtual"},{"valor":"presencial","etiqueta":"Presencial"}]},{"clave":"enlace_o_lugar","etiqueta":"Enlace o lugar","tipo":"text","requerido":true}]'),
              (3, 'audiencia_agendada', 'Audiencia agendada',
               'Confirma que la audiencia ocurrió antes de registrar su resultado.',
               '[{"clave":"audiencia_realizada","etiqueta":"La audiencia se realizó","tipo":"boolean","requerido":true}]'),
              (4, 'resultado_audiencia', 'Resultado de audiencia',
               'Registra lo ocurrido y la conclusión procesal de la audiencia.',
               '[{"clave":"resumen","etiqueta":"Resumen de la audiencia","tipo":"textarea","requerido":true},{"clave":"resultado","etiqueta":"Resultado","tipo":"select","requerido":true,"opciones":[{"valor":"acuerdo","etiqueta":"Acuerdo"},{"valor":"sin_acuerdo","etiqueta":"Sin acuerdo"}]}]'),
              (5, 'definicion', 'Definición',
               'Formaliza el acuerdo o el paso a liquidación patrimonial.',
               '[{"clave":"definicion","etiqueta":"Definición del trámite","tipo":"select","requerido":true,"opciones":[{"valor":"acuerdo","etiqueta":"Acuerdo confirmado"},{"valor":"fracaso","etiqueta":"Fracaso y paso a liquidación"}]},{"clave":"observaciones","etiqueta":"Observaciones","tipo":"textarea","requerido":true}]')
        ) AS step(orden, codigo, titulo, descripcion, campos)
        WHERE a.is_active = true
        """
    )
    op.execute(
        """
        UPDATE asuntos
        SET etapa_actual = 'Paso 1 de 5: Radicación',
            siguiente_paso = 'Registra la radicación oficial y la autoridad que recibe el trámite.',
            paso_actual = 1,
            flujo_estado = 'activo'
        WHERE is_active = true
        """
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asuntos', 'flujo_estado')
    op.drop_column('asuntos', 'paso_actual')
    op.drop_column('asuntos', 'ruta_codigo')
    op.drop_index(op.f('ix_asunto_pasos_is_active'), table_name='asunto_pasos')
    op.drop_index(op.f('ix_asunto_pasos_firma_id'), table_name='asunto_pasos')
    op.drop_index(op.f('ix_asunto_pasos_estado'), table_name='asunto_pasos')
    op.drop_index(op.f('ix_asunto_pasos_asunto_id'), table_name='asunto_pasos')
    op.drop_table('asunto_pasos')
    # ### end Alembic commands ###
