"""add_firma_storage_config_and_storage_folders

Revision ID: 698510deb624
Revises: e2efcc79ab70
Create Date: 2026-07-26 21:37:30.430107

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '698510deb624'
down_revision: Union[str, None] = 'e2efcc79ab70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma_storage_config',
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('auth_type', sa.String(length=30), nullable=False),
    sa.Column('oauth_refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('oauth_access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('oauth_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_folder_id', sa.String(length=255), nullable=True),
    sa.Column('root_folder_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firma_storage_config_firma_id'), 'firma_storage_config', ['firma_id'], unique=True)
    op.add_column('asuntos', sa.Column('storage_folders', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asuntos', 'storage_folders')
    op.drop_index(op.f('ix_firma_storage_config_firma_id'), table_name='firma_storage_config')
    op.drop_table('firma_storage_config')
    # ### end Alembic commands ###
