"""add workflow tasks

Revision ID: edf17141b1a1
Revises: 4d39af83fd4b
Create Date: 2026-07-28 22:23:35.864251

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf17141b1a1'
down_revision: Union[str, None] = '4d39af83fd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('asunto_id', sa.UUID(), nullable=False),
    sa.Column('asunto_paso_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('instruccion', sa.Text(), nullable=False),
    sa.Column('consecuencia', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=24), nullable=False),
    sa.Column('prioridad', sa.String(length=16), nullable=False),
    sa.Column('vence_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsable_id', sa.UUID(), nullable=False),
    sa.Column('solicitante_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'en_progreso', 'completada', 'cancelada')", name='ck_tarea_estado'),
    sa.CheckConstraint("prioridad IN ('baja', 'normal', 'alta', 'urgente')", name='ck_tarea_prioridad'),
    sa.ForeignKeyConstraint(['asunto_id'], ['asuntos.id'], ),
    sa.ForeignKeyConstraint(['asunto_paso_id'], ['asunto_pasos.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asunto_id', 'codigo', name='uq_tarea_asunto_codigo')
    )
    op.create_index('ix_tarea_asunto_estado', 'tareas', ['firma_id', 'asunto_id', 'estado'], unique=False)
    op.create_index('ix_tarea_bandeja', 'tareas', ['firma_id', 'responsable_id', 'estado', 'vence_en'], unique=False)
    op.create_index(op.f('ix_tareas_asunto_id'), 'tareas', ['asunto_id'], unique=False)
    op.create_index(op.f('ix_tareas_asunto_paso_id'), 'tareas', ['asunto_paso_id'], unique=False)
    op.create_index(op.f('ix_tareas_estado'), 'tareas', ['estado'], unique=False)
    op.create_index(op.f('ix_tareas_firma_id'), 'tareas', ['firma_id'], unique=False)
    op.create_index(op.f('ix_tareas_is_active'), 'tareas', ['is_active'], unique=False)
    op.create_index(op.f('ix_tareas_prioridad'), 'tareas', ['prioridad'], unique=False)
    op.create_index(op.f('ix_tareas_responsable_id'), 'tareas', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_tareas_vence_en'), 'tareas', ['vence_en'], unique=False)

    asuntos = sa.table(
        "asuntos",
        sa.column("id", sa.UUID()),
        sa.column("firma_id", sa.UUID()),
        sa.column("abogado_id", sa.UUID()),
        sa.column("created_by_id", sa.UUID()),
        sa.column("is_active", sa.Boolean()),
    )
    asunto_pasos = sa.table(
        "asunto_pasos",
        sa.column("id", sa.UUID()),
        sa.column("asunto_id", sa.UUID()),
        sa.column("codigo", sa.String()),
        sa.column("titulo", sa.String()),
        sa.column("descripcion", sa.String()),
        sa.column("estado", sa.String()),
        sa.column("is_active", sa.Boolean()),
    )
    tareas = sa.table(
        "tareas",
        sa.column("id", sa.UUID()),
        sa.column("firma_id", sa.UUID()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        sa.column("created_by_id", sa.UUID()),
        sa.column("asunto_id", sa.UUID()),
        sa.column("asunto_paso_id", sa.UUID()),
        sa.column("codigo", sa.String()),
        sa.column("tipo", sa.String()),
        sa.column("titulo", sa.String()),
        sa.column("instruccion", sa.Text()),
        sa.column("estado", sa.String()),
        sa.column("prioridad", sa.String()),
        sa.column("responsable_id", sa.UUID()),
        sa.column("solicitante_id", sa.UUID()),
    )

    connection = op.get_bind()
    active_steps = connection.execute(
        sa.select(
            asuntos.c.id.label("asunto_id"),
            asuntos.c.firma_id,
            asuntos.c.abogado_id,
            asuntos.c.created_by_id,
            asunto_pasos.c.id.label("paso_id"),
            asunto_pasos.c.codigo,
            asunto_pasos.c.titulo,
            asunto_pasos.c.descripcion,
        )
        .select_from(
            asuntos.join(asunto_pasos, asunto_pasos.c.asunto_id == asuntos.c.id)
        )
        .where(asuntos.c.is_active.is_(True))
        .where(asunto_pasos.c.is_active.is_(True))
        .where(asunto_pasos.c.estado == "activo")
    ).mappings()

    now = datetime.now(timezone.utc)
    rows = []
    for step in active_steps:
        responsible_id = step["abogado_id"] or step["created_by_id"]
        if responsible_id is None:
            raise RuntimeError(
                f"El asunto {step['asunto_id']} no tiene responsable para migrar su tarea activa"
            )
        rows.append(
            {
                "id": uuid.uuid4(),
                "firma_id": step["firma_id"],
                "is_active": True,
                "created_at": now,
                "updated_at": now,
                "created_by_id": step["created_by_id"] or responsible_id,
                "asunto_id": step["asunto_id"],
                "asunto_paso_id": step["paso_id"],
                "codigo": f"paso:{step['codigo']}",
                "tipo": "completar_paso",
                "titulo": f"Completar {step['titulo'].lower()}",
                "instruccion": step["descripcion"],
                "estado": "pendiente",
                "prioridad": "normal",
                "responsable_id": responsible_id,
                "solicitante_id": step["created_by_id"] or responsible_id,
            }
        )
    if rows:
        connection.execute(tareas.insert(), rows)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_vence_en'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_responsable_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_prioridad'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_is_active'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_firma_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_estado'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_asunto_paso_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_asunto_id'), table_name='tareas')
    op.drop_index('ix_tarea_bandeja', table_name='tareas')
    op.drop_index('ix_tarea_asunto_estado', table_name='tareas')
    op.drop_table('tareas')
    # ### end Alembic commands ###
