"""link documents and case activity

Revision ID: 472397b7561d
Revises: 24df9594e69c
Create Date: 2026-07-29 19:26:34.249387

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472397b7561d'
down_revision: Union[str, None] = '24df9594e69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_asunto', sa.Column('asunto_paso_id', sa.UUID(), nullable=True))
    op.add_column('documentos_asunto', sa.Column('subcarpeta', sa.String(length=30), server_default='anexo', nullable=False))
    op.create_index(op.f('ix_documentos_asunto_asunto_paso_id'), 'documentos_asunto', ['asunto_paso_id'], unique=False)
    op.create_foreign_key('fk_documento_asunto_paso', 'documentos_asunto', 'asunto_pasos', ['asunto_paso_id'], ['id'])
    op.add_column('novedades', sa.Column('asunto_paso_id', sa.UUID(), nullable=True))
    op.add_column('novedades', sa.Column('documento_id', sa.UUID(), nullable=True))
    op.add_column('novedades', sa.Column('tipo', sa.String(length=40), server_default='nota', nullable=False))
    op.create_index(op.f('ix_novedades_asunto_paso_id'), 'novedades', ['asunto_paso_id'], unique=False)
    op.create_index(op.f('ix_novedades_documento_id'), 'novedades', ['documento_id'], unique=False)
    op.create_index(op.f('ix_novedades_tipo'), 'novedades', ['tipo'], unique=False)
    op.create_foreign_key('fk_novedad_documento', 'novedades', 'documentos_asunto', ['documento_id'], ['id'])
    op.create_foreign_key('fk_novedad_asunto_paso', 'novedades', 'asunto_pasos', ['asunto_paso_id'], ['id'])
    # Actualiza únicamente las novedades determinísticas del entorno demo para
    # que no contradigan la ruta inicial migrada. No altera datos de usuarios.
    op.execute(
        """
        UPDATE novedades
        SET titulo = 'Documentos iniciales solicitados',
            descripcion = 'El equipo jurídico inició la recepción del asunto y solicitó la información necesaria para evaluar la solicitud.',
            updated_at = now()
        WHERE id = '00000000-0000-0000-0000-000000000301'
        """
    )
    op.execute(
        """
        UPDATE novedades
        SET titulo = 'Revisión inicial del asunto',
            descripcion = 'Validación interna de identidad, documentos disponibles y posibles conflictos antes de emitir una conclusión.',
            updated_at = now()
        WHERE id = '00000000-0000-0000-0000-000000000302'
        """
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_novedad_asunto_paso', 'novedades', type_='foreignkey')
    op.drop_constraint('fk_novedad_documento', 'novedades', type_='foreignkey')
    op.drop_index(op.f('ix_novedades_tipo'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_documento_id'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_asunto_paso_id'), table_name='novedades')
    op.drop_column('novedades', 'tipo')
    op.drop_column('novedades', 'documento_id')
    op.drop_column('novedades', 'asunto_paso_id')
    op.drop_constraint('fk_documento_asunto_paso', 'documentos_asunto', type_='foreignkey')
    op.drop_index(op.f('ix_documentos_asunto_asunto_paso_id'), table_name='documentos_asunto')
    op.drop_column('documentos_asunto', 'subcarpeta')
    op.drop_column('documentos_asunto', 'asunto_paso_id')
    # ### end Alembic commands ###
