"""add client responsibility

Revision ID: 72c3aad083a9
Revises: bd4dfc622675
Create Date: 2026-07-29 20:46:39.789940

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c3aad083a9'
down_revision: Union[str, None] = 'bd4dfc622675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('responsable_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_clientes_responsable_id'), 'clientes', ['responsable_id'], unique=False)
    op.create_foreign_key(
        'fk_clientes_responsable_id_users',
        'clientes',
        'users',
        ['responsable_id'],
        ['id'],
    )
    op.execute(
        """
        UPDATE clientes AS cliente
        SET responsable_id = (
            SELECT asunto.abogado_id
            FROM asuntos AS asunto
            WHERE asunto.cliente_id = cliente.id
              AND asunto.firma_id = cliente.firma_id
              AND asunto.is_active = true
              AND asunto.abogado_id IS NOT NULL
            ORDER BY asunto.created_at DESC, asunto.id DESC
            LIMIT 1
        )
        WHERE cliente.responsable_id IS NULL
          AND EXISTS (
              SELECT 1
              FROM asuntos AS asunto
              WHERE asunto.cliente_id = cliente.id
                AND asunto.firma_id = cliente.firma_id
                AND asunto.is_active = true
                AND asunto.abogado_id IS NOT NULL
          )
        """
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_clientes_responsable_id_users',
        'clientes',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_clientes_responsable_id'), table_name='clientes')
    op.drop_column('clientes', 'responsable_id')
    # ### end Alembic commands ###
