"""initial_subphase_1_schema

Revision ID: 512ffe7abb80
Revises: None
Create Date: 2026-07-26 08:06:50.678521

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512ffe7abb80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_procesales',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('color_tipo', sa.String(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_procesales_firma_id'), 'estados_procesales', ['firma_id'], unique=False)
    op.create_index(op.f('ix_estados_procesales_is_active'), 'estados_procesales', ['is_active'], unique=False)
    op.create_table('firmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('subdominio', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmas_subdominio'), 'firmas', ['subdominio'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cedula', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cedula'), 'users', ['cedula'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firma_id'), 'users', ['firma_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('asuntos',
    sa.Column('radicado', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('abogado_id', sa.UUID(), nullable=True),
    sa.Column('estado_id', sa.UUID(), nullable=True),
    sa.Column('etapa_actual', sa.String(length=255), nullable=False),
    sa.Column('siguiente_paso', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['abogado_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_procesales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asuntos_abogado_id'), 'asuntos', ['abogado_id'], unique=False)
    op.create_index(op.f('ix_asuntos_cliente_id'), 'asuntos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_asuntos_firma_id'), 'asuntos', ['firma_id'], unique=False)
    op.create_index(op.f('ix_asuntos_is_active'), 'asuntos', ['is_active'], unique=False)
    op.create_index(op.f('ix_asuntos_radicado'), 'asuntos', ['radicado'], unique=False)
    op.create_table('novedades',
    sa.Column('asunto_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('publicado_al_cliente', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asunto_id'], ['asuntos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novedades_asunto_id'), 'novedades', ['asunto_id'], unique=False)
    op.create_index(op.f('ix_novedades_firma_id'), 'novedades', ['firma_id'], unique=False)
    op.create_index(op.f('ix_novedades_is_active'), 'novedades', ['is_active'], unique=False)
    op.create_index(op.f('ix_novedades_publicado_al_cliente'), 'novedades', ['publicado_al_cliente'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novedades_publicado_al_cliente'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_is_active'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_firma_id'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_asunto_id'), table_name='novedades')
    op.drop_table('novedades')
    op.drop_index(op.f('ix_asuntos_radicado'), table_name='asuntos')
    op.drop_index(op.f('ix_asuntos_is_active'), table_name='asuntos')
    op.drop_index(op.f('ix_asuntos_firma_id'), table_name='asuntos')
    op.drop_index(op.f('ix_asuntos_cliente_id'), table_name='asuntos')
    op.drop_index(op.f('ix_asuntos_abogado_id'), table_name='asuntos')
    op.drop_table('asuntos')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_firma_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cedula'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_firmas_subdominio'), table_name='firmas')
    op.drop_table('firmas')
    op.drop_index(op.f('ix_estados_procesales_is_active'), table_name='estados_procesales')
    op.drop_index(op.f('ix_estados_procesales_firma_id'), table_name='estados_procesales')
    op.drop_table('estados_procesales')
    # ### end Alembic commands ###
