"""create_documentos_asunto_table

Revision ID: e2efcc79ab70
Revises: 512ffe7abb80
Create Date: 2026-07-26 17:08:28.130246

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2efcc79ab70'
down_revision: Union[str, None] = '512ffe7abb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_asunto',
    sa.Column('asunto_id', sa.UUID(), nullable=False),
    sa.Column('nombre_funcional', sa.String(length=255), nullable=False),
    sa.Column('tipo_documental', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_file_id', sa.String(length=255), nullable=False),
    sa.Column('web_view_url', sa.Text(), nullable=False),
    sa.Column('web_download_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=True),
    sa.Column('compartido_con_cliente', sa.Boolean(), nullable=False),
    sa.Column('estado_revision', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firma_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asunto_id'], ['asuntos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_asunto_asunto_id'), 'documentos_asunto', ['asunto_id'], unique=False)
    op.create_index(op.f('ix_documentos_asunto_firma_id'), 'documentos_asunto', ['firma_id'], unique=False)
    op.create_index(op.f('ix_documentos_asunto_is_active'), 'documentos_asunto', ['is_active'], unique=False)
    op.add_column('asuntos', sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asuntos', 'google_drive_folder_id')
    op.drop_index(op.f('ix_documentos_asunto_is_active'), table_name='documentos_asunto')
    op.drop_index(op.f('ix_documentos_asunto_firma_id'), table_name='documentos_asunto')
    op.drop_index(op.f('ix_documentos_asunto_asunto_id'), table_name='documentos_asunto')
    op.drop_table('documentos_asunto')
    # ### end Alembic commands ###
